// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerPanel.Data;

#nullable disable

namespace ServerPanel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605221216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerPanel.Models.VpsMetricSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("CpuPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("LoadAverage")
                        .HasColumnType("double precision");

                    b.Property<long>("MemoryTotalMb")
                        .HasColumnType("bigint");

                    b.Property<long>("MemoryUsedMb")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VpsMetricSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
